version: "3.8"

services:
  app:
    container_name: node-app
    image: nodejsapp:1
    ports:
    - 80:80
    networks:
    - octo_network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - 27017:27017
    restart: always
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
    - octo_network


networks:
  octo_network:
      external: true
