name: 'Terraform deploy'

on:
  push:
    branches:
    - main
    paths: 
    - alb/**
    - ec2/**
    - ecr/**
    - node-app/**
    - pyy-app/**
  pull_request:
    branches:
    - main
    paths: 
    - alb/**
    - ec2/**
    - ecr/**
    - node-app/**
    - pyy-app/**

permissions:
     contents: read
     pull-requests: write
    
jobs:
  terraform-ecr-s3:
   name: "ecr/s3"
   runs-on: ubuntu-latest
   defaults:
      run:
       shell: bash
       
   steps:
  # Checkout the repository to the GitHub Actions runner
   - name: Checkout
     uses: actions/checkout@v3
     
     
   - name: Install Terraform 
     uses: hashicorp/setup-terraform@v2
     
   
   - name:  Terraorm ecr/s3 init
     id: init
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform init
     
   - name: Terraform ecr/s3 plan
     id: plan 
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform plan -input=false
  
   - name: Terraform apply
     id: apply
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: |
       terraform apply -auto-approve -input=false
       terraform plan -destroy -out ecr-s3-plan

   - uses: actions/upload-artifact@v3
     with:
      name: ecr_s3-plan
      path: ecr-s3-plan
       

 


  tf-destroy-ecr-s3:
    name: destroy "ecr/s3"
    runs-on: ubuntu-latest
    #  defaults:
    #    run:
    #      shell: bash
    needs: terraform-ecr-s3
    if: success()
        
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v2
      
      
    - name: Install Terraform 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    
    
    - name: Terraform destroy
      id: apply
      env: 
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      working-directory: ./ecr
      run: terraform apply ecr-s3-plan