name: 'Terraform deploy'

on:
  push:
    branches:
    - main
    paths: 
    - alb/**
    - ec2/**
    - ecr/**
    - node-app/**
    - pyy-app/**
  pull_request:
    branches:
    - main
    paths: 
    - alb/**
    - ec2/**
    - ecr/**
    - node-app/**
    - pyy-app/**

permissions:
     contents: read
     pull-requests: write
    
jobs:
  terraform:
   name: "ecr"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       
   steps:
  # Checkout the repository to the GitHub Actions runner
   - name: Checkout
     uses: actions/checkout@v3
     with:
       terraform_wrapper: false
     
   - name: Install Terraform 
     run: |
       wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
       echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
       sudo apt update && sudo apt install terraform
   
   - name:  Terraorm ecr init
     id: init
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform init
     
   - name: Terraform ecr plan
     id: plan 
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform plan -input=false 
    
  
   
   
