name: 'Terraform deploy'

on:
  push:
    branches:
    - main
    paths: 
    - alb/**
    - ec2/**
    - ecr/**
    - node-app/**
    - pyy-app/**
  pull_request:
    branches:
    - main
    paths: 
    - alb/**
    - ec2/**
    - ecr/**
    - node-app/**
    - pyy-app/**

permissions:
     contents: read
     pull-requests: write
    
jobs:
  terraform-ecr:
   name: "ecr"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       
   steps:
  # Checkout the repository to the GitHub Actions runner
   - name: Checkout
     uses: actions/checkout@v3
     with:
      terraform_wrapper: false
     
   - name: Install Terraform 
     run: |
       wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
       echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
       sudo apt update && sudo apt install terraform
   
   - name:  Terraorm ecr init
     id: init
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform init
     
   - name: Terraform ecr plan
     id: plan 
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform plan -input=false
  
   - name: Terraform apply
     id: apply
     env: 
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
     working-directory: ./ecr
     run: terraform apply -auto-approve -input=false

 
  build-image:
    name: "build and push"
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout build
      uses: actions/checkout@v3
      with:
        terraform_wrapper: false
      
    - name: Configs AWS crdentails 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-central-1
    
    - name: login to ecr
      id: login-ecr 
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Tag abd push images to Amazon ECR 
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: devone
        IMAGE_TAG: devone_v1
      working-directory: ./node-app
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  
   
   
